CREATE TABLE IF NOT EXISTS PUBLIC.TASK_STATUS_STG(
    ID VARCHAR(20),
    LOG_TYPE VARCHAR(20),
    HOST VARCHAR(20),
    START_TIME BIGINT,
    END_TIME BIGINT
);
--TRUNCATE TABLE PUBLIC.TASK_STATUS_STG ;