INSERT INTO PUBLIC.TASK_STATUS_FCT(
    SELECT ID, END_TIME-START_TIME, LOG_TYPE, HOST, (END_TIME-START_TIME) > 4 FROM
        (
        SELECT ID, max(START_TIME) as START_TIME, max(END_TIME) as END_TIME, max(LOG_TYPE) as LOG_TYPE, max(HOST) as HOST FROM
            PUBLIC.TASK_STATUS_STG group by ID
        )
) ;